### ISSUE TITLE
Uncaught (in promise) Error     at o (shallowEqual.js:18)

### ISSUE THREAD

**Issue by qadir-genetech** [smooch/smooch-bot-example#40]
Smooch web widget not loading.
I am getting this when inspecting element.

![image](https://user-images.githubusercontent.com/14326497/42867544-58699b40-8a89-11e8-8e2b-5893e31d9c56.png)

```
Failed to load resource: the server responded with a status of 401 ()
shallowEqual.js:18 Uncaught (in promise) Error
    at o (shallowEqual.js:18)
```

Any feeback please.

**Comment by qadir-genetech** [comment]
looks something wrong with shallowEqual.js

![image](https://user-images.githubusercontent.com/14326497/42867890-4820fa66-8a8a-11e8-8019-5f8e7bb2c51a.png)

I have found this shallowEqual.js file while googling.
https://gist.github.com/tanat/3d695499ac1a4525ab221583838e6bdb#file-shallowequal-js-L19
it has something differences on line 18/19

**Comment by qadir-genetech** [comment]
any feeback on this please. our smooch web-interface is down.

**Comment by alavers** [comment]
My suspicion is that there is some polyfill or something else in the host page that is messing with `Object.prototype.hasOwnProperty`.

`smooch-bot-example` is using a fairly old version of Smooch Web Messenger ([3.15.2](https://github.com/alavers/smooch-bot-example/blob/master/views/index.hbs#L3))

The latest version is 4.12.10, and since version 4 the chat UI loads inside its own iframe, which prevents js env interference such as this. Could you try latest version of Smooch web messenger? Instructions [here](https://docs.smooch.io/guide/web-messenger#script-tag-method)

**Comment by qadir-genetech** [comment]
Great. its working :) 👍 💯 🥇
