### ISSUE TITLE
Question: Customization and typing indicator

### ISSUE THREAD

**Issue by nachio** [smooch/smooch-bot-example#6]
Not so much an issue, more a question on how to use smooch bot to recreate your Smooch conversational onboarding experience (which I love!).

Your onboarding UI is full screen and starts immediately with a question. Then before each reply from your bot a typing indicator is shown. Can all this (full screen, let the bot initiate the conversation and show a typing indicator) be achieved with this framework? 

Any help or pointers would be greatly appreciated! In any case this is awesome stuff!

**Comment by alavers** [comment]
> Can all this (full screen, let the bot initiate the conversation and show a typing indicator) be achieved with this framework?

In short, yes, but much of the onboarding UI was heavily customized and is not reusable, so you would have to do much of it yourself.

The conversation script of the Smooch onboarding uses this state machine model, so that part would be easy to do. However, from your questions it sounds like you're interested in the UI as well. The onboarding chat UI was derived from our web widget, smooch/smooch-js, but it was very heavily modified, things like setting up a Smooch app using your company name and automatically detecting when certain steps were completed, all of that was custom built front and back for the specific onboarding experience we wanted.

The goal of smooch/smooch-bot however is to be a offer a more generic framework, without any assumptions made about the UI.

With that said, I can give you some pointers.

1) Without any code changes you can run the smooch/smooch-js widget in full screen by running it in [embedded mode](https://github.com/smooch/smooch-js#embedded-mode).

2) Simulating the bot's typing indicators requires a little more work. The way we did this was very hackish to be honest. We set a kind of "bot will respond" flag in each bot message's [metadata](http://docs.smooch.io/rest/#post-message) and assuming that flag was there we rendered a fake typing indicator client side as soon as the user sent a message.

3) The bot response delay is also simulated. We compute the delay based on the length of the bot's message. You can do this easily in your bot's `say()` implmementation by simply delaying the promise resolution with [Q.delay](https://github.com/kriskowal/q#using-qfcall), or your own favorite promise implementation.

4) Finally, the immediate first message you see in the onboarding experience is actually implemented as a Smooch [whisper](http://docs.smooch.io/javascript/#whispers), which we trigger with a [track](http://docs.smooch.io/rest/#track-event) call.

I hope that gives you something useful to work off of :)

**Comment by nachio** [comment]
This is amazing. Thank you so much for the pointers and an overview. Enough to get me on my way. Thanks again!
